// Raw word list data — no framework imports, safe to use in both Next.js and PartyKit

export const CATEGORIES = [
  'Animals', 'AsianFood', 'Celebrities', 'Cities', 'FictionalCharacter',
  'Food', 'Hobbies', 'Jobs', 'Movies', 'Sports',
] as const

export const WORD_DATA: Record<string, string[]> = {
  Animals: [
    "Alligator", "Antelope", "Baboon", "Badger", "Beaver", "Buffalo",
    "Capybara", "Cheetah", "Chicken", "Coyote", "Dolphin", "Donkey",
    "Eagle", "Elephant", "Falcon", "Fox", "Giraffe", "Gorilla",
    "Hamster", "Hippo", "Horse", "Jaguar", "Jellyfish", "Kangaroo",
    "Koala", "Leopard", "Lion", "Lizard", "Monkey", "Ostrich",
    "Panda", "Penguin", "Rabbit", "Raccoon", "Shark", "Sloth",
    "Tiger", "Wolf", "Zebra",
  ],
  AsianFood: [
    "Banh Mi", "Bao", "Bibimbap", "Bulgogi", "Butter Chicken",
    "Chow Mein", "Dumpling", "Edamame", "Fried Rice",
    "Hotpot", "Kimchi", "Kimbap", "Mochi",
    "Noodles", "Onigiri", "Pad Thai", "Peking Duck", "Pho",
    "Ramen", "Samosa", "Sashimi", "Spring Roll", "Sushi",
    "Tempura", "Teriyaki", "Tofu", "Udon",
  ],
  Celebrities: [
    "Adele", "Ariana Grande", "Bad Bunny", "Beyonce", "Billie Eilish",
    "Bruno Mars", "Chris Rock", "Cristiano Ronaldo", "Doja Cat", "Drake",
    "Dua Lipa", "Ed Sheeran", "Eminem", "Harry Styles", "Justin Bieber",
    "Kanye West", "Katy Perry", "Kylie Jenner", "Lady Gaga", "LeBron James",
    "Lionel Messi", "Madonna", "MrBeast", "Nicki Minaj", "Olivia Rodrigo",
    "Post Malone", "Rihanna", "Selena Gomez", "Snoop Dogg", "Taylor Swift",
    "The Weeknd", "Timothee Chalamet", "Tom Holland", "Travis Scott", "Zendaya",
  ],
  Cities: [
    "Amsterdam", "Athens", "Austin", "Bangkok", "Barcelona",
    "Beijing", "Berlin", "Boston", "Brussels", "Budapest",
    "Cairo", "Cape Town", "Chicago", "Dallas", "Denver",
    "Dubai", "Dublin", "Edinburgh", "Istanbul", "Jakarta",
    "Kuala Lumpur", "Lagos", "Lisbon", "London", "Los Angeles",
    "Madrid", "Manila", "Melbourne", "Miami", "Milan",
    "Moscow", "Mumbai", "Munich", "Nashville", "New York",
    "Osaka", "Paris", "Prague", "Rome", "Santiago",
    "Seattle", "Seoul", "Shanghai", "Singapore", "Sydney",
    "Taipei", "Tokyo", "Toronto", "Venice", "Vienna",
    "Warsaw", "Zurich",
  ],
  FictionalCharacter: [
    "Batman", "Bugs Bunny", "Darth Vader", "Deadpool", "Dumbledore",
    "Elsa", "Frodo", "Gandalf", "Goku", "Harry Potter",
    "Hermione", "Homer Simpson", "Iron Man", "Jack Sparrow", "James Bond",
    "Joker", "Katniss", "Luke Skywalker", "Mario",
    "Mickey Mouse", "Naruto", "Pac-Man", "Peter Griffin", "Pikachu",
    "Sherlock Holmes", "Shrek", "Snoopy", "Sonic", "Spider-Man",
    "SpongeBob", "Superman", "Thanos", "Winnie-the-Pooh", "Wolverine",
    "Yoda", "Zelda",
  ],
  Food: [
    "Apple", "Avocado", "Bacon", "Bagel", "Banana",
    "Brownie", "Burger", "Burrito", "Cake", "Cheese",
    "Cherry", "Chicken", "Chocolate", "Cookie", "Croissant",
    "Curry", "Donut", "Falafel", "Garlic", "Grapes",
    "Hummus", "Lasagna", "Lemon", "Mango", "Matcha",
    "Melon", "Nachos", "Omelette", "Onion", "Orange",
    "Pancake", "Pasta", "Peach", "Pie", "Pizza",
    "Potato", "Salad", "Salmon", "Sandwich", "Sorbet",
    "Steak", "Strawberry", "Sushi", "Tacos", "Toast",
    "Waffle", "Yogurt",
  ],
  Hobbies: [
    "Archery", "Baking", "Bowling", "Camping", "Chess",
    "Coding", "Cooking", "Cycling", "Dancing", "Drawing",
    "Fishing", "Gaming", "Gardening", "Hiking", "Hunting",
    "Jogging", "Karate", "Knitting", "Origami", "Painting",
    "Photography", "Pilates", "Poker", "Pottery", "Puzzle",
    "Reading", "Rowing", "Running", "Sailing", "Sewing",
    "Singing", "Skating", "Skiing", "Soccer", "Surfing",
    "Tennis", "Travel", "Woodworking", "Writing", "Yoga",
  ],
  Jobs: [
    "Accountant", "Actor", "Architect", "Artist", "Astronaut",
    "Banker", "Barber", "Carpenter", "Chef", "Dentist",
    "Designer", "Doctor", "Driver", "Electrician", "Engineer",
    "Farmer", "Firefighter", "Judge", "Journalist", "Lawyer",
    "Librarian", "Mechanic", "Musician", "Nurse", "Painter",
    "Pharmacist", "Photographer", "Pilot", "Plumber", "Police Officer",
    "Professor", "Programmer", "Scientist", "Security Guard", "Social Worker",
    "Soldier", "Surgeon", "Teacher", "Therapist", "Veterinarian",
  ],
  Movies: [
    "Aladdin", "Avatar", "Avengers", "Barbie", "Batman",
    "Cinderella", "Coraline", "Deadpool", "Frozen",
    "Gladiator", "Godzilla", "Harry Potter", "Inception", "Incredibles",
    "Inside Out", "Interstellar", "Iron Man", "Jaws", "Joker",
    "Jumanji", "La La Land", "Lion King", "Matrix", "Minions",
    "Moana", "Paranormal Activity", "Ratatouille", "Scream", "Shrek",
    "Skyfall", "Superman", "Titanic", "Transformers", "Twilight",
    "Whiplash",
  ],
  Sports: [
    "Archery", "Badminton", "Baseball", "Basketball", "Billiards",
    "Bowling", "Boxing", "Cricket", "Curling", "Cycling",
    "Diving", "Fencing", "Football", "Golf", "Gymnastics",
    "Handball", "Hockey", "Judo", "Karate", "Lacrosse",
    "Polo", "Racing", "Rowing", "Rugby", "Sailing",
    "Skating", "Skiing", "Soccer", "Softball", "Squash",
    "Surfing", "Swimming", "Tennis", "Volleyball", "Weightlifting",
    "Wrestling",
  ],
}
